### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Trapulo** [lweeks/zabbix_hp_c7000#1]
Hi,
I copied MIB files from HP to /usr/share/snmp/mibs. Restarted the entire server. The Zabbix template seems not working: it does not discover nothing :(

Any idea?
thanks

**Comment by lweeks** [comment]
Is just discovery not working? Do the built-in items work? If just discovery, did you try to force an immediate discovery?

If nothing works, test from your zabbix server/proxy like:

```
$ snmpwalk -cpublic -v2c hp-c7k-oa-1 CPQRACK-MIB::cpqRackCommonEnclosureFWRev.1
CPQRACK-MIB::cpqRackCommonEnclosureFWRev.1 = STRING: "4.60"
```

If that does not return an expected value then either the MIB files are not properly installed or the chassis administrator is not configured properly.

If it appears to be a MIB issue, try a numeric OID query:

```
$ snmpwalk -cpublic -v2c hp-c7k-oa-1 .1.3.6.1.4.1.232.22.2.3.1.1.1.8.1
.1.3.6.1.4.1.232.22.2.3.1.1.1.8.1 = STRING: "4.60"
```

**Comment by Trapulo** [comment]
Ops, after the entire night I found that it's collecting data. :)
thank you for support and for the template
